#!/usr/bin/env python3
"""Enable Codex Browser Use local-testing mode (macOS + Windows).

Codex Browser Use calls https://chatgpt.com/backend-api/aura/site_status
before every navigation. That cloud check blocks legitimate sites
(Taobao, 1688, Pixiv, ...) even when the user allowlisted them.

The bundled plugin already understands:

    BROWSER_USE_SECURITY_MODE=disabled-for-local-testing

which adds `check-url-site-status` (and friends) to bypassedSecurityChecks,
so `check-url-site-status` is skipped entirely. This tool turns that flag on
locally and, optionally, expands origin allowlists. Codex/ChatGPT updates
rewrite ~/.codex/config.toml; `install --persist` installs a watcher that
re-applies the same patch (LaunchAgent on macOS, Scheduled Task on Windows).

Platform differences
--------------------
macOS: the flag is injected by pointing [mcp_servers.node_repl] `command` at a
       bash wrapper that exports the variable and `exec`s the signed node_repl
       (keeps the native-pipe code-signing identity intact).

Windows: no wrapper is needed or wanted. [mcp_servers.node_repl] already has an
       `env` table that Codex passes to node_repl.exe, so the variable is set
       there directly and `command` is left untouched.
"""
from __future__ import annotations

import argparse
import json
import os
import plistlib
import re
import shutil
import stat
import subprocess
import sys
from datetime import datetime
from pathlib import Path

MODE = "disabled-for-local-testing"
LABEL = "com.codex-browser-lab.repair"
WIN_TASK = "CodexBrowserLabRepair"
WIN_TASK_LOGON = "CodexBrowserLabRepairLogon"
DEFAULT_WIN_INTERVAL_MIN = 5
PRESETS = {
    "shopping-cn": [
        "taobao.com",
        "tmall.com",
        "1688.com",
        "alicdn.com",
        "alipay.com",
    ],
}

IS_WIN = sys.platform == "win32"
IS_MAC = sys.platform == "darwin"

WRAPPER_BODY = r"""#!/usr/bin/env bash
# Generated by codex-browser-lab. exec keeps the signed node_repl image.
set -euo pipefail
export BROWSER_USE_SECURITY_MODE="${BROWSER_USE_SECURITY_MODE:-disabled-for-local-testing}"

candidates=(
  "/Applications/ChatGPT.app/Contents/Resources/cua_node/bin/node_repl"
  "/Applications/Codex.app/Contents/Resources/cua_node/bin/node_repl"
)
bin=""
for c in "${candidates[@]}"; do
  if [[ -x "$c" ]]; then
    bin="$c"
    break
  fi
done
if [[ -z "$bin" ]]; then
  echo "codex-browser-lab: node_repl not found in ChatGPT.app or Codex.app" >&2
  exit 1
fi
exec "$bin" "$@"
"""


# --------------------------------------------------------------------------
# paths
# --------------------------------------------------------------------------
def home() -> Path:
    return Path.home()


def codex_home() -> Path:
    return Path(os.environ.get("CODEX_HOME", home() / ".codex"))


def wrappers_dir() -> Path:
    return codex_home() / "mcp-wrappers"


def wrapper_path() -> Path:
    return wrappers_dir() / "node-repl-security-mode.sh"


def win_repair_cmd() -> Path:
    return wrappers_dir() / "codex-browser-lab-repair.cmd"


def installed_script() -> Path:
    return wrappers_dir() / "codex-browser-lab.py"


def state_path() -> Path:
    return wrappers_dir() / "codex-browser-lab.state.json"


def log_path() -> Path:
    return wrappers_dir() / "codex-browser-lab.log"


def launch_agent_path() -> Path:
    return home() / "Library" / "LaunchAgents" / f"{LABEL}.plist"


def config_toml() -> Path:
    return codex_home() / "config.toml"


def browser_toml() -> Path:
    return codex_home() / "browser" / "config.toml"


def plugin_cache() -> Path:
    return codex_home() / "plugins" / "cache" / "openai-bundled"


def windows_cua_root() -> Path:
    local = os.environ.get("LOCALAPPDATA") or str(home() / "AppData" / "Local")
    return Path(local) / "OpenAI" / "Codex" / "runtimes" / "cua_node"


# --------------------------------------------------------------------------
# text io (UTF-8; never trust the Windows ANSI codepage)
# --------------------------------------------------------------------------
def read_text(path: Path) -> str:
    data = path.read_bytes()
    if data.startswith(b"\xef\xbb\xbf"):
        return data.decode("utf-8-sig")
    if data.startswith(b"\xff\xfe"):
        return data.decode("utf-16")
    if data.startswith(b"\xfe\xff"):
        return data.decode("utf-16")
    return data.decode("utf-8")


def write_text(path: Path, text: str) -> None:
    path.write_bytes(text.encode("utf-8"))


# --------------------------------------------------------------------------
# discovery
# --------------------------------------------------------------------------
def _config_node_repl_command() -> Path | None:
    cfg = config_toml()
    if not cfg.exists():
        return None
    try:
        text = read_text(cfg)
    except (OSError, UnicodeDecodeError):
        return None
    span = table_span(text, "mcp_servers.node_repl")
    if span is None:
        return None
    m = re.search(
        r"""(?m)^\s*command\s*=\s*(['"])(.*?)\1\s*$""", text[span[0] : span[1]]
    )
    if not m:
        return None
    p = Path(m.group(2))
    return p if p.is_file() else None


def official_node_repl() -> Path | None:
    if IS_WIN:
        cfg_cmd = _config_node_repl_command()
        if cfg_cmd is not None and cfg_cmd.name.lower() == "node_repl.exe":
            return cfg_cmd
        root = windows_cua_root()
        if root.is_dir():
            try:
                cands = sorted(
                    root.glob("*/bin/node_repl.exe"),
                    key=lambda p: p.stat().st_mtime,
                    reverse=True,
                )
            except OSError:
                cands = []
            for c in cands:
                if c.is_file():
                    return c
        return None
    for p in (
        Path("/Applications/ChatGPT.app/Contents/Resources/cua_node/bin/node_repl"),
        Path("/Applications/Codex.app/Contents/Resources/cua_node/bin/node_repl"),
    ):
        if p.is_file():
            return p
    return None


def log(msg: str, *, quiet: bool = False, important: bool = False) -> None:
    if important or not quiet:
        print(msg, flush=True)


# --------------------------------------------------------------------------
# TOML surgery (text-level, so comments/ordering elsewhere survive)
# --------------------------------------------------------------------------
def table_span(text: str, name: str) -> tuple[int, int] | None:
    start = None
    for m in re.finditer(r"(?m)^\[([^\]]+)\][ \t]*\r?\n", text):
        if m.group(1) == name and start is None:
            start = m.start()
            continue
        if start is not None:
            return start, m.start()
    if start is None:
        return None
    return start, len(text)


def ensure_table(text: str, table: str) -> str:
    """Create `[table]` (right after its parent table) when it does not exist."""
    if table_span(text, table) is not None:
        return text
    block = f"[{table}]\n"
    if "." in table:
        parent = table.rsplit(".", 1)[0]
        span = table_span(text, parent)
        if span is not None:
            head = text[: span[1]].rstrip("\n")
            return f"{head}\n\n{block}\n{text[span[1] :]}"
    return text.rstrip("\n") + f"\n\n{block}"


def set_key(text: str, table: str, key: str, value: str) -> str:
    span = table_span(text, table)
    if span is None:
        raise SystemExit(f"missing TOML table [{table}] in {config_toml()}")
    body = text[span[0] : span[1]]
    pattern = re.compile(rf"(?m)^({re.escape(key)}\s*=\s*).+$")
    quoted = json.dumps(value, ensure_ascii=False)
    if pattern.search(body):
        body = pattern.sub(rf"\1{quoted}", body, count=1)
    else:
        lines = body.splitlines(keepends=True)
        if lines and not lines[-1].endswith("\n"):
            lines[-1] += "\n"
        insert_at = len(lines)
        for i, line in enumerate(lines):
            if line.startswith("BROWSER_USE_TINYSKY_ENABLED") or line.startswith(
                "BROWSER_USE_AVAILABLE_BACKENDS"
            ):
                insert_at = i + 1
        lines.insert(insert_at, f"{key} = {quoted}\n")
        body = "".join(lines)
    return text[: span[0]] + body + text[span[1] :]


def remove_key(text: str, table: str, key: str) -> str:
    span = table_span(text, table)
    if span is None:
        return text
    body = text[span[0] : span[1]]
    body = re.sub(rf"(?m)^{re.escape(key)}\s*=\s*.+\r?\n?", "", body)
    return text[: span[0]] + body + text[span[1] :]


def get_key(text: str, table: str, key: str) -> str | None:
    span = table_span(text, table)
    if span is None:
        return None
    m = re.search(
        rf"""(?m)^\s*{re.escape(key)}\s*=\s*(['"])(.*?)\1\s*$""",
        text[span[0] : span[1]],
    )
    return m.group(2) if m else None


def origin_table(host_pattern: str) -> str:
    return (
        f'[browser_use.origins."{host_pattern}"]\n'
        "access = \"allow\"\n"
        "downloads = \"allow\"\n"
        "uploads = \"allow\"\n"
        "full_cdp_access = \"allow\"\n"
    )


def ensure_origin_tables(text: str, domains: list[str]) -> str:
    blocks: list[str] = []
    for domain in domains:
        for key in (f"https://{domain}", f"https://**.{domain}"):
            header = f'[browser_use.origins."{key}"]'
            if header in text:
                continue
            blocks.append(origin_table(key).rstrip())
    if not blocks:
        return text
    addon = "\n\n" + "\n\n".join(blocks) + "\n"
    last_name = None
    for m in re.finditer(r"(?m)^\[(browser_use\.origins\.[^\]]+)\]", text):
        last_name = m.group(1)
    if last_name:
        span = table_span(text, last_name)
        assert span is not None
        return text[: span[1]].rstrip() + addon + text[span[1] :]
    span = table_span(text, "mcp_servers.node_repl.env")
    if span is not None:
        return text[: span[1]].rstrip() + addon + text[span[1] :]
    return text.rstrip() + addon


def merge_allowed_array(text: str, table: str, urls: list[str]) -> str:
    span = table_span(text, table)
    if span is None:
        return text
    body = text[span[0] : span[1]]
    m = re.search(r"(?ms)^(allowed\s*=\s*)\[(.*?)\]", body)
    if not m:
        return text
    existing = re.findall(r'"([^"]+)"', m.group(2))
    merged = list(existing)
    for url in urls:
        if url not in merged:
            merged.append(url)
    if merged == existing:
        return text
    inner = ",\n".join(f'  "{u}"' for u in merged)
    new_array = f"{m.group(1)}[\n{inner},\n]"
    body = body[: m.start()] + new_array + body[m.end() :]
    return text[: span[0]] + body + text[span[1] :]


# --------------------------------------------------------------------------
# patching
# --------------------------------------------------------------------------
def backup(path: Path) -> None:
    """Copy `path` aside before it is rewritten.

    The backup name is derived from the path *relative to CODEX_HOME*, so files
    that share a basename (`config.toml` vs `browser/config.toml`) can never
    overwrite each other's backup.
    """
    if not path.exists():
        return
    dest_dir = wrappers_dir() / "backups"
    dest_dir.mkdir(parents=True, exist_ok=True)
    try:
        rel = path.resolve().relative_to(codex_home().resolve())
        stem = "_".join(rel.parts)
    except (ValueError, OSError):
        stem = path.name
    stamp = datetime.now().strftime("%Y%m%d%H%M%S")
    dest = dest_dir / f"{stem}.{stamp}"
    n = 2
    while dest.exists():
        dest = dest_dir / f"{stem}.{stamp}-{n}"
        n += 1
    shutil.copy2(path, dest)


def ensure_wrapper(*, dry: bool, quiet: bool) -> Path:
    path = wrapper_path()
    if dry:
        return path
    path.parent.mkdir(parents=True, exist_ok=True)
    if not path.exists() or read_text(path) != WRAPPER_BODY:
        write_text(path, WRAPPER_BODY)
    path.chmod(path.stat().st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)
    log(f"wrapper: {path}", quiet=quiet)
    return path


def patch_config(domains: list[str], *, dry: bool, quiet: bool) -> bool:
    path = config_toml()
    if not path.exists():
        raise SystemExit(f"missing {path}; is Codex/ChatGPT installed?")
    text = read_text(path)
    if table_span(text, "mcp_servers.node_repl") is None:
        raise SystemExit(f"no [mcp_servers.node_repl] in {path}")
    original = text
    if IS_WIN:
        # Codex hands this env table straight to node_repl.exe; no wrapper needed.
        text = ensure_table(text, "mcp_servers.node_repl.env")
        text = set_key(text, "mcp_servers.node_repl.env", "BROWSER_USE_SECURITY_MODE", MODE)
    else:
        text = set_key(text, "mcp_servers.node_repl", "command", str(wrapper_path()))
        text = ensure_table(text, "mcp_servers.node_repl.env")
        text = set_key(text, "mcp_servers.node_repl.env", "BROWSER_USE_SECURITY_MODE", MODE)
    if domains:
        text = ensure_origin_tables(text, domains)
    if text == original:
        log(f"unchanged: {path}", quiet=quiet)
        return False
    if dry:
        log(f"would patch: {path}", quiet=quiet)
        return True
    backup(path)
    write_text(path, text)
    log(f"patched: {path}", quiet=quiet, important=True)
    return True


def patch_browser_config(domains: list[str], *, dry: bool, quiet: bool) -> bool:
    if not domains:
        return False
    path = browser_toml()
    urls: list[str] = []
    for domain in domains:
        urls.append(f"https://{domain}")
        urls.append(f"https://*.{domain}")
    if not path.exists():
        body = (
            'approval_mode = "never_ask"\n'
            'history_approval_mode = "never_ask"\n'
            'download_approval_mode = "never_ask"\n'
            'upload_approval_mode = "never_ask"\n'
            "full_cdp_access_enabled = true\n\n"
        )
        for table in ("origins", "downloads", "uploads", "full_cdp"):
            inner = ",\n".join(f'  "{u}"' for u in urls)
            body += f"[{table}]\nallowed = [\n{inner},\n]\ndenied = []\n\n"
        if dry:
            log(f"would create: {path}", quiet=quiet)
            return True
        path.parent.mkdir(parents=True, exist_ok=True)
        write_text(path, body)
        log(f"created: {path}", quiet=quiet)
        return True
    text = read_text(path)
    original = text
    for table in ("origins", "downloads", "uploads", "full_cdp"):
        text = merge_allowed_array(text, table, urls)
    if text == original:
        log(f"unchanged: {path}", quiet=quiet)
        return False
    if dry:
        log(f"would patch: {path}", quiet=quiet)
        return True
    backup(path)
    write_text(path, text)
    log(f"patched: {path}", quiet=quiet, important=True)
    return True


def patch_cua_mcp(*, dry: bool, quiet: bool) -> int:
    root = plugin_cache() / "unified-computer-use"
    if not root.exists():
        log("no unified-computer-use plugin cache (skip)", quiet=quiet)
        return 0
    changed = 0
    wrap = str(wrapper_path())
    for mcp in sorted(root.glob("*/.mcp.json")):
        data = json.loads(read_text(mcp))
        env = data.get("mcpServers", {}).get("cua_repl", {}).get("env")
        if not isinstance(env, dict):
            continue
        before = dict(env)
        env["BROWSER_USE_SECURITY_MODE"] = MODE
        if not IS_WIN:
            # macOS routes the child through the exec wrapper. On Windows there
            # is nothing to wrap, so the official node_repl path stays as-is.
            env["CUA_REPL_NODE_REPL_PATH"] = wrap
        if env == before:
            continue
        if dry:
            log(f"would patch: {mcp}", quiet=quiet)
            changed += 1
            continue
        backup(mcp)
        write_text(mcp, json.dumps(data, indent=2, ensure_ascii=False) + "\n")
        log(f"patched: {mcp}", quiet=quiet, important=True)
        changed += 1
    return changed


# --------------------------------------------------------------------------
# state + self-install
# --------------------------------------------------------------------------
def save_state(domains: list[str], preset: str | None, interval: int | None = None) -> None:
    wrappers_dir().mkdir(parents=True, exist_ok=True)
    payload = {
        "preset": preset,
        "domains": domains,
        "python": sys.executable,
    }
    if interval is not None:
        payload["interval_min"] = interval
    write_text(state_path(), json.dumps(payload, indent=2) + "\n")


def load_state() -> dict:
    if not state_path().exists():
        return {"domains": [], "preset": None}
    try:
        return json.loads(read_text(state_path()))
    except (OSError, ValueError):
        return {"domains": [], "preset": None}


def install_self(*, quiet: bool) -> None:
    src = Path(__file__).resolve()
    dst = installed_script()
    dst.parent.mkdir(parents=True, exist_ok=True)
    if src != dst:
        shutil.copy2(src, dst)
        if not IS_WIN:
            dst.chmod(dst.stat().st_mode | stat.S_IXUSR)
    log(f"installed tool: {dst}", quiet=quiet)


# --------------------------------------------------------------------------
# persistence: macOS LaunchAgent
# --------------------------------------------------------------------------
def persist_macos(*, quiet: bool) -> None:
    install_self(quiet=quiet)
    agent = launch_agent_path()
    agent.parent.mkdir(parents=True, exist_ok=True)
    plist = {
        "Label": LABEL,
        "ProgramArguments": [
            sys.executable,
            str(installed_script()),
            "repair",
        ],
        "WatchPaths": [
            str(config_toml()),
            str(plugin_cache()),
        ],
        "RunAtLoad": True,
        "StandardOutPath": str(log_path()),
        "StandardErrorPath": str(log_path()),
    }
    agent.write_bytes(plistlib.dumps(plist))
    uid = os.getuid()
    target = f"gui/{uid}"
    subprocess.run(["launchctl", "bootout", target, str(agent)], check=False, capture_output=True)
    subprocess.run(["launchctl", "unload", str(agent)], check=False, capture_output=True)
    loaded = subprocess.run(
        ["launchctl", "bootstrap", target, str(agent)], capture_output=True, text=True
    )
    if loaded.returncode != 0:
        loaded = subprocess.run(
            ["launchctl", "load", str(agent)], capture_output=True, text=True
        )
    if loaded.returncode != 0:
        raise SystemExit(loaded.stderr.strip() or "launchctl load failed")
    log(f"persist: {agent}", quiet=quiet)


def unpersist_macos(*, quiet: bool) -> None:
    agent = launch_agent_path()
    if agent.exists():
        uid = os.getuid()
        subprocess.run(
            ["launchctl", "bootout", f"gui/{uid}", str(agent)],
            check=False,
            capture_output=True,
        )
        subprocess.run(["launchctl", "unload", str(agent)], check=False, capture_output=True)
        agent.unlink()
        log(f"removed LaunchAgent: {agent}", quiet=quiet)
    else:
        log("no LaunchAgent installed", quiet=quiet)


# --------------------------------------------------------------------------
# persistence: Windows Scheduled Task
# --------------------------------------------------------------------------
def _python_for_task() -> str:
    exe = Path(sys.executable)
    if IS_WIN:
        pyw = exe.with_name("pythonw.exe")
        if pyw.exists():
            return str(pyw)
    return str(exe)


def write_repair_cmd(*, quiet: bool) -> Path:
    """Tiny .cmd shim so the scheduled task never needs nested quoting."""
    cmd = win_repair_cmd()
    cmd.parent.mkdir(parents=True, exist_ok=True)
    body = (
        "@echo off\r\n"
        "rem Generated by codex-browser-lab; re-applies the security-mode patch.\r\n"
        f'"{_python_for_task()}" "{installed_script()}" repair >> "{log_path()}" 2>&1\r\n'
    )
    if not cmd.exists() or read_text(cmd) != body:
        write_text(cmd, body)
    log(f"repair shim: {cmd}", quiet=quiet)
    return cmd


def _schtasks(*args: str) -> subprocess.CompletedProcess:
    return subprocess.run(
        ["schtasks", *args], capture_output=True, text=True, errors="replace"
    )


def persist_windows(*, quiet: bool, interval: int = DEFAULT_WIN_INTERVAL_MIN) -> None:
    if interval < 1:
        interval = 1
    install_self(quiet=quiet)
    shim = write_repair_cmd(quiet=quiet)
    tr = f'"{shim}"'
    created: list[str] = []
    errors: list[str] = []

    r = _schtasks(
        "/Create", "/TN", WIN_TASK, "/TR", tr,
        "/SC", "MINUTE", "/MO", str(interval), "/F",
    )
    if r.returncode == 0:
        created.append(WIN_TASK)
    else:
        errors.append(f"{WIN_TASK}: {(r.stderr or r.stdout).strip()}")

    r = _schtasks("/Create", "/TN", WIN_TASK_LOGON, "/TR", tr, "/SC", "ONLOGON", "/F")
    if r.returncode == 0:
        created.append(WIN_TASK_LOGON)
    else:
        errors.append(f"{WIN_TASK_LOGON}: {(r.stderr or r.stdout).strip()}")

    if not created:
        raise SystemExit("could not register a scheduled task:\n  " + "\n  ".join(errors))
    for name in created:
        log(f"persist: scheduled task {name}", quiet=quiet)
    for err in errors:
        log(f"warn: task not registered - {err}", quiet=quiet, important=True)
    if WIN_TASK_LOGON not in created:
        log(
            "note: the logon task is optional. Registering an ONLOGON trigger needs an "
            "elevated shell; the periodic task already re-applies the patch shortly "
            "after a reboot.",
            quiet=quiet,
        )


def unpersist_windows(*, quiet: bool) -> None:
    removed = False
    for name in (WIN_TASK, WIN_TASK_LOGON):
        r = _schtasks("/Delete", "/TN", name, "/F")
        if r.returncode == 0:
            log(f"removed scheduled task: {name}", quiet=quiet)
            removed = True
    if not removed:
        log("no scheduled task installed", quiet=quiet)
    shim = win_repair_cmd()
    if shim.exists():
        shim.unlink()
        log(f"removed repair shim: {shim}", quiet=quiet)


def persist(*, quiet: bool, interval: int = DEFAULT_WIN_INTERVAL_MIN) -> None:
    if IS_MAC:
        persist_macos(quiet=quiet)
    elif IS_WIN:
        persist_windows(quiet=quiet, interval=interval)
    else:
        raise SystemExit("--persist is supported on macOS and Windows only")


def unpersist(*, quiet: bool) -> None:
    if IS_MAC:
        unpersist_macos(quiet=quiet)
    elif IS_WIN:
        unpersist_windows(quiet=quiet)


def _task_state(name: str) -> str:
    r = _schtasks("/Query", "/TN", name)
    if r.returncode == 0:
        return "installed"
    message = f"{r.stdout or ''} {r.stderr or ''}".lower()
    if "cannot find" in message or "找不到" in message:
        return "absent"
    # A denied/failed query must not be reported as "absent".
    return "unknown"


def persist_status() -> str:
    if IS_MAC:
        agent = launch_agent_path()
        return f"LaunchAgent {agent} exists={agent.exists()}"
    if IS_WIN:
        return " ".join(
            f"{name}={_task_state(name)}" for name in (WIN_TASK, WIN_TASK_LOGON)
        )
    return "n/a"


# --------------------------------------------------------------------------
# live process inspection
# --------------------------------------------------------------------------
def _windows_node_repl_pids() -> list[int]:
    """Enumerate node_repl.exe via toolhelp32 (no external tool, no shell)."""
    import ctypes
    from ctypes import wintypes

    TH32CS_SNAPPROCESS = 0x00000002
    INVALID_HANDLE_VALUE = ctypes.c_void_p(-1).value

    class PROCESSENTRY32W(ctypes.Structure):
        _fields_ = [
            ("dwSize", wintypes.DWORD),
            ("cntUsage", wintypes.DWORD),
            ("th32ProcessID", wintypes.DWORD),
            ("th32DefaultHeapID", ctypes.POINTER(ctypes.c_ulong)),
            ("th32ModuleID", wintypes.DWORD),
            ("cntThreads", wintypes.DWORD),
            ("th32ParentProcessID", wintypes.DWORD),
            ("pcPriClassBase", ctypes.c_long),
            ("dwFlags", wintypes.DWORD),
            ("szExeFile", wintypes.WCHAR * 260),
        ]

    k32 = ctypes.WinDLL("kernel32", use_last_error=True)
    k32.CreateToolhelp32Snapshot.restype = ctypes.c_void_p
    k32.CreateToolhelp32Snapshot.argtypes = [wintypes.DWORD, wintypes.DWORD]
    k32.Process32FirstW.argtypes = [ctypes.c_void_p, ctypes.POINTER(PROCESSENTRY32W)]
    k32.Process32NextW.argtypes = [ctypes.c_void_p, ctypes.POINTER(PROCESSENTRY32W)]
    k32.CloseHandle.argtypes = [ctypes.c_void_p]

    snapshot = k32.CreateToolhelp32Snapshot(TH32CS_SNAPPROCESS, 0)
    if not snapshot or snapshot == INVALID_HANDLE_VALUE:
        return []
    pids: list[int] = []
    try:
        entry = PROCESSENTRY32W()
        entry.dwSize = ctypes.sizeof(PROCESSENTRY32W)
        ok = k32.Process32FirstW(ctypes.c_void_p(snapshot), ctypes.byref(entry))
        while ok:
            if entry.szExeFile.lower() == "node_repl.exe":
                pids.append(int(entry.th32ProcessID))
            ok = k32.Process32NextW(ctypes.c_void_p(snapshot), ctypes.byref(entry))
    finally:
        k32.CloseHandle(ctypes.c_void_p(snapshot))
    return pids


def _read_windows_process_env(pid: int) -> dict[str, str] | None:
    """Read another same-user process's environment block via its PEB (read-only)."""
    import ctypes
    from ctypes import wintypes

    PROCESS_QUERY_INFORMATION = 0x0400
    PROCESS_VM_READ = 0x0010

    k32 = ctypes.WinDLL("kernel32", use_last_error=True)
    ntdll = ctypes.WinDLL("ntdll", use_last_error=True)

    k32.OpenProcess.restype = ctypes.c_void_p
    k32.OpenProcess.argtypes = [wintypes.DWORD, wintypes.BOOL, wintypes.DWORD]
    k32.ReadProcessMemory.restype = wintypes.BOOL
    k32.ReadProcessMemory.argtypes = [
        ctypes.c_void_p,
        ctypes.c_void_p,
        ctypes.c_void_p,
        ctypes.c_size_t,
        ctypes.POINTER(ctypes.c_size_t),
    ]
    k32.CloseHandle.argtypes = [ctypes.c_void_p]
    ntdll.NtQueryInformationProcess.restype = ctypes.c_long
    ntdll.NtQueryInformationProcess.argtypes = [
        ctypes.c_void_p,
        ctypes.c_ulong,
        ctypes.c_void_p,
        ctypes.c_ulong,
        ctypes.POINTER(ctypes.c_ulong),
    ]

    class PROCESS_BASIC_INFORMATION(ctypes.Structure):
        _fields_ = [
            ("Reserved1", ctypes.c_void_p),
            ("PebBaseAddress", ctypes.c_void_p),
            ("Reserved2", ctypes.c_void_p * 2),
            ("UniqueProcessId", ctypes.c_void_p),
            ("Reserved3", ctypes.c_void_p),
        ]

    handle = k32.OpenProcess(PROCESS_QUERY_INFORMATION | PROCESS_VM_READ, False, pid)
    if not handle:
        return None
    try:
        pbi = PROCESS_BASIC_INFORMATION()
        ret = ctypes.c_ulong(0)
        status = ntdll.NtQueryInformationProcess(
            ctypes.c_void_p(handle), 0, ctypes.byref(pbi),
            ctypes.sizeof(pbi), ctypes.byref(ret),
        )
        if status != 0 or not pbi.PebBaseAddress:
            return None

        def read_ptr(address: int) -> int | None:
            buf = ctypes.c_void_p()
            n = ctypes.c_size_t(0)
            ok = k32.ReadProcessMemory(
                ctypes.c_void_p(handle), ctypes.c_void_p(address),
                ctypes.byref(buf), ctypes.sizeof(buf), ctypes.byref(n),
            )
            return buf.value if ok else None

        # PEB->ProcessParameters (x64 +0x20), then
        # RTL_USER_PROCESS_PARAMETERS->Environment (x64 +0x80).
        params = read_ptr(pbi.PebBaseAddress + 0x20)
        if not params:
            return None
        env_ptr = read_ptr(params + 0x80)
        if not env_ptr:
            return None

        blob = bytearray()
        address = env_ptr
        chunk = 4096
        while len(blob) < 1024 * 1024:
            buf = ctypes.create_string_buffer(chunk)
            n = ctypes.c_size_t(0)
            ok = k32.ReadProcessMemory(
                ctypes.c_void_p(handle), ctypes.c_void_p(address),
                buf, chunk, ctypes.byref(n),
            )
            if not ok or n.value == 0:
                break
            blob += buf.raw[: n.value]
            if blob.endswith(b"\x00\x00"):
                break
            address += n.value

        text = bytes(blob).decode("utf-16-le", errors="replace")
        env: dict[str, str] = {}
        for item in text.split("\x00"):
            if not item or item.startswith("=") or "=" not in item:
                continue
            key, value = item.split("=", 1)
            env[key] = value
        return env
    except OSError:
        return None
    finally:
        k32.CloseHandle(ctypes.c_void_p(handle))


def live_node_repl() -> list[tuple[str, str]]:
    if IS_WIN:
        rows = []
        for pid in _windows_node_repl_pids():
            env = _read_windows_process_env(pid)
            if env is None:
                rows.append((str(pid), "<unreadable>"))
            else:
                rows.append((str(pid), env.get("BROWSER_USE_SECURITY_MODE", "<unset>")))
        return rows
    try:
        pids = subprocess.check_output(
            ["pgrep", "-f", "/cua_node/bin/node_repl"], text=True
        )
    except (subprocess.CalledProcessError, FileNotFoundError):
        return []
    rows = []
    for pid in pids.split():
        try:
            env = subprocess.check_output(
                ["ps", "eww", "-p", pid], text=True, errors="replace"
            )
        except subprocess.CalledProcessError:
            continue
        mode = "<unset>"
        for part in env.replace(" ", "\n").split("\n"):
            if part.startswith("BROWSER_USE_SECURITY_MODE="):
                mode = part.split("=", 1)[1]
                break
        rows.append((pid, mode))
    return rows


# --------------------------------------------------------------------------
# commands
# --------------------------------------------------------------------------
def cmd_install(args: argparse.Namespace) -> int:
    domains = list(args.allow)
    if args.preset:
        domains.extend(PRESETS[args.preset])
    seen: set[str] = set()
    uniq: list[str] = []
    for d in domains:
        d = d.strip().lower().lstrip(".")
        if d and d not in seen:
            seen.add(d)
            uniq.append(d)

    node_repl = official_node_repl()
    if node_repl is None:
        target = "Codex/ChatGPT node_repl" if IS_WIN else "ChatGPT.app / Codex.app node_repl"
        raise SystemExit(f"{target} not found")
    if IS_WIN:
        log(f"node_repl: {node_repl}", quiet=args.quiet)
    else:
        ensure_wrapper(dry=args.dry_run, quiet=args.quiet)

    patch_config(uniq, dry=args.dry_run, quiet=args.quiet)
    patch_browser_config(uniq, dry=args.dry_run, quiet=args.quiet)
    patch_cua_mcp(dry=args.dry_run, quiet=args.quiet)
    if not args.dry_run:
        interval = getattr(args, "interval", None)
        save_state(uniq, args.preset, interval)
        if args.persist:
            persist(quiet=args.quiet, interval=interval or DEFAULT_WIN_INTERVAL_MIN)
        else:
            install_self(quiet=args.quiet)
    restart_hint = "restart Codex / ChatGPT Desktop" if IS_WIN else "restart ChatGPT.app"
    log(
        f"done. start a NEW Codex thread (or {restart_hint}) so node_repl picks up the env.",
        quiet=args.quiet,
    )
    return 0


def cmd_repair(args: argparse.Namespace) -> int:
    state = load_state()
    ns = argparse.Namespace(
        allow=state.get("domains") or [],
        preset=None,
        persist=False,
        dry_run=False,
        quiet=True,
        interval=state.get("interval_min"),
    )
    try:
        return cmd_install(ns)
    except SystemExit as exc:
        _append_log(f"repair failed: {exc}")
        raise
    except Exception as exc:  # noqa: BLE001 - a watcher must never die loudly
        _append_log(f"repair error: {exc!r}")
        return 1


def _append_log(line: str) -> None:
    try:
        wrappers_dir().mkdir(parents=True, exist_ok=True)
        stamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        with log_path().open("a", encoding="utf-8") as fh:
            fh.write(f"{stamp} {line}\n")
    except OSError:
        pass


def cmd_uninstall(args: argparse.Namespace) -> int:
    unpersist(quiet=args.quiet)
    path = config_toml()
    if path.exists():
        text = read_text(path)
        bin_path = official_node_repl()
        if not IS_WIN and bin_path is not None and table_span(text, "mcp_servers.node_repl"):
            text = set_key(text, "mcp_servers.node_repl", "command", str(bin_path))
        text = remove_key(text, "mcp_servers.node_repl.env", "BROWSER_USE_SECURITY_MODE")
        if not args.dry_run:
            write_text(path, text)
            log(f"restored node_repl in {path}", quiet=args.quiet)
    root = plugin_cache() / "unified-computer-use"
    wrap = str(wrapper_path())
    bin_path = official_node_repl()
    if root.exists():
        for mcp in root.glob("*/.mcp.json"):
            data = json.loads(read_text(mcp))
            env = data.get("mcpServers", {}).get("cua_repl", {}).get("env")
            if not isinstance(env, dict):
                continue
            env.pop("BROWSER_USE_SECURITY_MODE", None)
            if bin_path is not None and env.get("CUA_REPL_NODE_REPL_PATH") == wrap:
                env["CUA_REPL_NODE_REPL_PATH"] = str(bin_path)
            if not args.dry_run:
                write_text(mcp, json.dumps(data, indent=2, ensure_ascii=False) + "\n")
                log(f"restored {mcp}", quiet=args.quiet)
    log("origin allowlists were left in place; delete them manually if you want.", quiet=args.quiet)
    return 0


def cmd_status(args: argparse.Namespace) -> int:
    print(f"platform            {sys.platform}")
    print(f"CODEX_HOME          {codex_home()}")
    if IS_WIN:
        print(f"official node_repl  {official_node_repl()}")
        print(f"persist             {persist_status()}")
        print(f"repair shim         {win_repair_cmd()} exists={win_repair_cmd().exists()}")
    else:
        print(f"wrapper             {wrapper_path()} exists={wrapper_path().exists()}")
        print(f"official node_repl  {official_node_repl()}")
        print(f"LaunchAgent         {launch_agent_path()} exists={launch_agent_path().exists()}")

    cfg = config_toml()
    ok = False
    if cfg.exists():
        text = read_text(cfg)
        cmd = get_key(text, "mcp_servers.node_repl", "command")
        mode = get_key(text, "mcp_servers.node_repl.env", "BROWSER_USE_SECURITY_MODE")
        print(f"config command      {cmd}")
        print(f"config security     {mode}")
        if IS_WIN:
            official = official_node_repl()
            # On Windows `command` must remain the official binary.
            cmd_ok = official is not None and cmd is not None and Path(cmd) == official
        else:
            cmd_ok = cmd == str(wrapper_path())
        ok = cmd_ok and mode == MODE
        print(f"config ok           {ok}")
    else:
        print("config.toml         missing")

    rows = live_node_repl()
    if not rows:
        print("live node_repl      (none)")
    for pid, mode in rows:
        print(f"live pid={pid:<10} mode={mode}")
    if not ok:
        return 2
    if rows and all(m != MODE for _, m in rows):
        print("note: live processes still have the old env; start a new Codex thread.")
        return 3
    return 0


def build_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(
        prog="codex-browser-lab",
        description="Turn on Codex Browser Use local-testing mode (skip aura/site_status).",
    )
    sub = p.add_subparsers(dest="cmd", required=True)

    def add_common(sp: argparse.ArgumentParser) -> None:
        sp.add_argument("--dry-run", action="store_true")
        sp.add_argument("--quiet", action="store_true")

    ins = sub.add_parser("install", help="patch local Codex/ChatGPT config")
    add_common(ins)
    ins.add_argument(
        "--persist",
        action="store_true",
        help="install a watcher that re-applies after updates "
        "(macOS LaunchAgent / Windows Scheduled Task)",
    )
    ins.add_argument(
        "--interval",
        type=int,
        metavar="MIN",
        help=f"Windows: re-check period in minutes (default {DEFAULT_WIN_INTERVAL_MIN})",
    )
    ins.add_argument("--preset", choices=sorted(PRESETS), help="origin allowlist preset")
    ins.add_argument(
        "--allow", action="append", default=[], metavar="DOMAIN",
        help="repeatable, e.g. --allow pixiv.net",
    )
    ins.set_defaults(func=cmd_install)

    st = sub.add_parser("status", help="show whether the patch is active")
    add_common(st)
    st.set_defaults(func=cmd_status)

    un = sub.add_parser("uninstall", help="restore official node_repl; keep origin allowlists")
    add_common(un)
    un.set_defaults(func=cmd_uninstall)

    rp = sub.add_parser("repair", help="re-apply last install (used by the watcher)")
    add_common(rp)
    rp.set_defaults(func=cmd_repair)

    return p


def main(argv: list[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    return args.func(args)


if __name__ == "__main__":
    sys.exit(main())
