#!/usr/bin/env python3
"""Enable Codex Browser Use local-testing mode.

Codex Browser Use calls https://chatgpt.com/backend-api/aura/site_status
before every navigation. That cloud check blocks legitimate sites
(Taobao, 1688, Pixiv, …) even when the user allowlisted them.

The bundled plugin already understands:

    BROWSER_USE_SECURITY_MODE=disabled-for-local-testing

which skips check-url-site-status. This tool turns that flag on locally
and, optionally, expands origin allowlists. ChatGPT/Codex updates rewrite
~/.codex/config.toml; `install --persist` installs a LaunchAgent that
re-applies the same patch.
"""
from __future__ import annotations

import argparse
import json
import os
import plistlib
import re
import shutil
import stat
import subprocess
import sys
from datetime import datetime
from pathlib import Path

MODE = "disabled-for-local-testing"
LABEL = "com.codex-browser-lab.repair"
PRESETS = {
    "shopping-cn": [
        "taobao.com",
        "tmall.com",
        "1688.com",
        "alicdn.com",
        "alipay.com",
    ],
}

WRAPPER_BODY = r"""#!/usr/bin/env bash
# Generated by codex-browser-lab. exec keeps the signed node_repl image.
set -euo pipefail
export BROWSER_USE_SECURITY_MODE="${BROWSER_USE_SECURITY_MODE:-disabled-for-local-testing}"

candidates=(
  "/Applications/ChatGPT.app/Contents/Resources/cua_node/bin/node_repl"
  "/Applications/Codex.app/Contents/Resources/cua_node/bin/node_repl"
)
bin=""
for c in "${candidates[@]}"; do
  if [[ -x "$c" ]]; then
    bin="$c"
    break
  fi
done
if [[ -z "$bin" ]]; then
  echo "codex-browser-lab: node_repl not found in ChatGPT.app or Codex.app" >&2
  exit 1
fi
exec "$bin" "$@"
"""


def home() -> Path:
    return Path.home()


def codex_home() -> Path:
    return Path(os.environ.get("CODEX_HOME", home() / ".codex"))


def wrappers_dir() -> Path:
    return codex_home() / "mcp-wrappers"


def wrapper_path() -> Path:
    return wrappers_dir() / "node-repl-security-mode.sh"


def installed_script() -> Path:
    return wrappers_dir() / "codex-browser-lab.py"


def state_path() -> Path:
    return wrappers_dir() / "codex-browser-lab.state.json"


def log_path() -> Path:
    return wrappers_dir() / "codex-browser-lab.log"


def launch_agent_path() -> Path:
    return home() / "Library" / "LaunchAgents" / f"{LABEL}.plist"


def config_toml() -> Path:
    return codex_home() / "config.toml"


def browser_toml() -> Path:
    return codex_home() / "browser" / "config.toml"


def plugin_cache() -> Path:
    return codex_home() / "plugins" / "cache" / "openai-bundled"


def official_node_repl() -> Path | None:
    for p in (
        Path("/Applications/ChatGPT.app/Contents/Resources/cua_node/bin/node_repl"),
        Path("/Applications/Codex.app/Contents/Resources/cua_node/bin/node_repl"),
    ):
        if p.is_file():
            return p
    return None


def log(msg: str, *, quiet: bool = False, important: bool = False) -> None:
    if important or not quiet:
        print(msg, flush=True)


def table_span(text: str, name: str) -> tuple[int, int] | None:
    header = f"[{name}]"
    start = None
    for m in re.finditer(r"(?m)^\[([^\]]+)\][ \t]*\r?\n", text):
        if m.group(1) == name and start is None:
            start = m.start()
            continue
        if start is not None:
            return start, m.start()
    if start is None:
        return None
    return start, len(text)


def set_key(text: str, table: str, key: str, value: str) -> str:
    span = table_span(text, table)
    if span is None:
        raise SystemExit(f"missing TOML table [{table}] in {config_toml()}")
    body = text[span[0] : span[1]]
    pattern = re.compile(rf"(?m)^({re.escape(key)}\s*=\s*).+$")
    quoted = json.dumps(value, ensure_ascii=False)
    if pattern.search(body):
        body = pattern.sub(rf"\1{quoted}", body, count=1)
    else:
        lines = body.splitlines(keepends=True)
        if lines and not lines[-1].endswith("\n"):
            lines[-1] += "\n"
        insert_at = len(lines)
        for i, line in enumerate(lines):
            if line.startswith("BROWSER_USE_TINYSKY_ENABLED") or line.startswith(
                "BROWSER_USE_AVAILABLE_BACKENDS"
            ):
                insert_at = i + 1
        lines.insert(insert_at, f"{key} = {quoted}\n")
        body = "".join(lines)
    return text[: span[0]] + body + text[span[1] :]


def remove_key(text: str, table: str, key: str) -> str:
    span = table_span(text, table)
    if span is None:
        return text
    body = text[span[0] : span[1]]
    body = re.sub(rf"(?m)^{re.escape(key)}\s*=\s*.+\r?\n?", "", body)
    return text[: span[0]] + body + text[span[1] :]


def origin_table(host_pattern: str) -> str:
    return (
        f'[browser_use.origins."{host_pattern}"]\n'
        "access = \"allow\"\n"
        "downloads = \"allow\"\n"
        "uploads = \"allow\"\n"
        "full_cdp_access = \"allow\"\n"
    )


def ensure_origin_tables(text: str, domains: list[str]) -> str:
    blocks: list[str] = []
    for domain in domains:
        for key in (f"https://{domain}", f"https://**.{domain}"):
            header = f'[browser_use.origins."{key}"]'
            if header in text:
                continue
            blocks.append(origin_table(key).rstrip())
    if not blocks:
        return text
    addon = "\n\n" + "\n\n".join(blocks) + "\n"
    last_name = None
    for m in re.finditer(r"(?m)^\[(browser_use\.origins\.[^\]]+)\]", text):
        last_name = m.group(1)
    if last_name:
        span = table_span(text, last_name)
        assert span is not None
        return text[: span[1]].rstrip() + addon + text[span[1] :]
    span = table_span(text, "mcp_servers.node_repl.env")
    if span is not None:
        return text[: span[1]].rstrip() + addon + text[span[1] :]
    return text.rstrip() + addon


def merge_allowed_array(text: str, table: str, urls: list[str]) -> str:
    span = table_span(text, table)
    if span is None:
        return text
    body = text[span[0] : span[1]]
    m = re.search(r"(?ms)^(allowed\s*=\s*)\[(.*?)\]", body)
    if not m:
        return text
    existing = re.findall(r'"([^"]+)"', m.group(2))
    merged = list(existing)
    for url in urls:
        if url not in merged:
            merged.append(url)
    if merged == existing:
        return text
    inner = ",\n".join(f'  "{u}"' for u in merged)
    new_array = f"{m.group(1)}[\n{inner},\n]"
    body = body[: m.start()] + new_array + body[m.end() :]
    return text[: span[0]] + body + text[span[1] :]


def write_if_changed(path: Path, content: str, *, dry: bool) -> bool:
    old = path.read_text() if path.exists() else None
    if old == content:
        return False
    if dry:
        return True
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content)
    return True


def backup(path: Path) -> None:
    if not path.exists():
        return
    dest_dir = wrappers_dir() / "backups"
    dest_dir.mkdir(parents=True, exist_ok=True)
    stamp = datetime.now().strftime("%Y%m%d%H%M%S")
    shutil.copy2(path, dest_dir / f"{path.name}.{stamp}")


def ensure_wrapper(*, dry: bool, quiet: bool) -> Path:
    path = wrapper_path()
    if dry:
        return path
    path.parent.mkdir(parents=True, exist_ok=True)
    if not path.exists() or path.read_text() != WRAPPER_BODY:
        path.write_text(WRAPPER_BODY)
    path.chmod(path.stat().st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)
    log(f"wrapper: {path}", quiet=quiet)
    return path


def patch_config(domains: list[str], *, dry: bool, quiet: bool) -> bool:
    path = config_toml()
    if not path.exists():
        raise SystemExit(f"missing {path}; is Codex/ChatGPT installed?")
    text = path.read_text()
    if table_span(text, "mcp_servers.node_repl") is None:
        raise SystemExit(f"no [mcp_servers.node_repl] in {path}")
    original = text
    text = set_key(text, "mcp_servers.node_repl", "command", str(wrapper_path()))
    text = set_key(text, "mcp_servers.node_repl.env", "BROWSER_USE_SECURITY_MODE", MODE)
    if domains:
        text = ensure_origin_tables(text, domains)
    if text == original:
        log(f"unchanged: {path}", quiet=quiet)
        return False
    if dry:
        log(f"would patch: {path}", quiet=quiet)
        return True
    backup(path)
    path.write_text(text)
    log(f"patched: {path}", quiet=quiet, important=True)
    return True


def patch_browser_config(domains: list[str], *, dry: bool, quiet: bool) -> bool:
    if not domains:
        return False
    path = browser_toml()
    urls: list[str] = []
    for domain in domains:
        urls.append(f"https://{domain}")
        urls.append(f"https://*.{domain}")
    if not path.exists():
        body = (
            'approval_mode = "never_ask"\n'
            'history_approval_mode = "never_ask"\n'
            'download_approval_mode = "never_ask"\n'
            'upload_approval_mode = "never_ask"\n'
            "full_cdp_access_enabled = true\n\n"
        )
        for table in ("origins", "downloads", "uploads", "full_cdp"):
            inner = ",\n".join(f'  "{u}"' for u in urls)
            body += f"[{table}]\nallowed = [\n{inner},\n]\ndenied = []\n\n"
        if dry:
            log(f"would create: {path}", quiet=quiet)
            return True
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(body)
        log(f"created: {path}", quiet=quiet)
        return True
    text = path.read_text()
    original = text
    for table in ("origins", "downloads", "uploads", "full_cdp"):
        text = merge_allowed_array(text, table, urls)
    if text == original:
        log(f"unchanged: {path}", quiet=quiet)
        return False
    if dry:
        log(f"would patch: {path}", quiet=quiet)
        return True
    backup(path)
    path.write_text(text)
    log(f"patched: {path}", quiet=quiet, important=True)
    return True


def patch_cua_mcp(*, dry: bool, quiet: bool) -> int:
    root = plugin_cache() / "unified-computer-use"
    if not root.exists():
        log("no unified-computer-use plugin cache (skip)", quiet=quiet)
        return 0
    changed = 0
    wrap = str(wrapper_path())
    for mcp in sorted(root.glob("*/.mcp.json")):
        data = json.loads(mcp.read_text())
        env = (
            data.get("mcpServers", {})
            .get("cua_repl", {})
            .get("env")
        )
        if not isinstance(env, dict):
            continue
        before = dict(env)
        env["BROWSER_USE_SECURITY_MODE"] = MODE
        env["CUA_REPL_NODE_REPL_PATH"] = wrap
        if env == before:
            continue
        if dry:
            log(f"would patch: {mcp}", quiet=quiet)
            changed += 1
            continue
        backup(mcp)
        mcp.write_text(json.dumps(data, indent=2, ensure_ascii=False) + "\n")
        log(f"patched: {mcp}", quiet=quiet, important=True)
        changed += 1
    return changed


NAV_BLOCK_RE = re.compile(
    r"(function \w+\(\w+\)\{if\(\w+==null\|\|!\w+\(\w+\)\)return;)"
    r"(let \w+=\w+\(\w+\.params\.url\)\?\?\"this page\";"
    r"throw new \w+\(\"browser_navigation_blocked\","
    r"`Browser Use is not permitted on \$\{\w+\}\.`\)\})"
)
NAV_BLOCK_GUARD = (
    'if((typeof process<"u"?process.env.BROWSER_USE_SECURITY_MODE:"")'
    '==="disabled-for-local-testing")return;'
)


def patch_navigation_blocked(*, dry: bool, quiet: bool) -> int:
    """Ignore Chrome Page.navigationBlocked under local-testing mode.

    site_status is skipped by the env flag, but in-page actions can still
    throw browser_navigation_blocked ("not permitted on <url>") when CDP
    emits Page.navigationBlocked — common on mp.weixin.qq.com admin flows.
    """
    changed = 0
    roots = [plugin_cache() / "chrome", plugin_cache() / "browser"]
    files: list[Path] = []
    for root in roots:
        if root.exists():
            files.extend(sorted(root.glob("*/scripts/browser-service.mjs")))
    for path in files:
        text = path.read_text(errors="replace")
        if NAV_BLOCK_GUARD in text:
            continue
        new, n = NAV_BLOCK_RE.subn(r"\1" + NAV_BLOCK_GUARD + r"\2", text, count=1)
        if n == 0:
            log(f"no Page.navigationBlocked hook in {path} (skip)", quiet=quiet)
            continue
        if dry:
            log(f"would patch navigationBlocked: {path}", quiet=quiet)
            changed += 1
            continue
        backup(path)
        path.write_text(new)
        log(f"patched navigationBlocked: {path}", quiet=quiet, important=True)
        changed += 1
    return changed


def save_state(domains: list[str], preset: str | None) -> None:
    wrappers_dir().mkdir(parents=True, exist_ok=True)
    state_path().write_text(
        json.dumps(
            {
                "preset": preset,
                "domains": domains,
                "python": sys.executable,
            },
            indent=2,
        )
        + "\n"
    )


def load_state() -> dict:
    if not state_path().exists():
        return {"domains": [], "preset": None}
    return json.loads(state_path().read_text())


def install_self(*, quiet: bool) -> None:
    src = Path(__file__).resolve()
    dst = installed_script()
    dst.parent.mkdir(parents=True, exist_ok=True)
    if src != dst:
        shutil.copy2(src, dst)
        dst.chmod(dst.stat().st_mode | stat.S_IXUSR)
    log(f"installed tool: {dst}", quiet=quiet)


def persist(*, quiet: bool) -> None:
    if sys.platform != "darwin":
        raise SystemExit("--persist is macOS-only (LaunchAgent)")
    install_self(quiet=quiet)
    agent = launch_agent_path()
    agent.parent.mkdir(parents=True, exist_ok=True)
    plist = {
        "Label": LABEL,
        "ProgramArguments": [
            sys.executable,
            str(installed_script()),
            "repair",
        ],
        "WatchPaths": [
            str(config_toml()),
            str(plugin_cache()),
        ],
        "RunAtLoad": True,
        "StandardOutPath": str(log_path()),
        "StandardErrorPath": str(log_path()),
    }
    agent.write_bytes(plistlib.dumps(plist))
    uid = os.getuid()
    target = f"gui/{uid}"
    subprocess.run(["launchctl", "bootout", target, str(agent)], check=False, capture_output=True)
    subprocess.run(["launchctl", "unload", str(agent)], check=False, capture_output=True)
    loaded = subprocess.run(
        ["launchctl", "bootstrap", target, str(agent)], capture_output=True, text=True
    )
    if loaded.returncode != 0:
        loaded = subprocess.run(
            ["launchctl", "load", str(agent)], capture_output=True, text=True
        )
    if loaded.returncode != 0:
        raise SystemExit(loaded.stderr.strip() or "launchctl load failed")
    log(f"persist: {agent}", quiet=quiet)


def unpersist(*, quiet: bool) -> None:
    agent = launch_agent_path()
    if agent.exists():
        uid = os.getuid()
        subprocess.run(
            ["launchctl", "bootout", f"gui/{uid}", str(agent)],
            check=False,
            capture_output=True,
        )
        subprocess.run(["launchctl", "unload", str(agent)], check=False, capture_output=True)
        agent.unlink()
        log(f"removed LaunchAgent: {agent}", quiet=quiet)
    else:
        log("no LaunchAgent installed", quiet=quiet)


def cmd_install(args: argparse.Namespace) -> int:
    domains = list(args.allow)
    if args.preset:
        domains.extend(PRESETS[args.preset])
    # de-dupe, keep order
    seen: set[str] = set()
    uniq: list[str] = []
    for d in domains:
        d = d.strip().lower().lstrip(".")
        if d and d not in seen:
            seen.add(d)
            uniq.append(d)
    if official_node_repl() is None:
        raise SystemExit("ChatGPT.app / Codex.app node_repl not found")
    ensure_wrapper(dry=args.dry_run, quiet=args.quiet)
    patch_config(uniq, dry=args.dry_run, quiet=args.quiet)
    patch_browser_config(uniq, dry=args.dry_run, quiet=args.quiet)
    patch_cua_mcp(dry=args.dry_run, quiet=args.quiet)
    patch_navigation_blocked(dry=args.dry_run, quiet=args.quiet)
    if not args.dry_run:
        save_state(uniq, args.preset)
        if args.persist:
            persist(quiet=args.quiet)
        else:
            install_self(quiet=args.quiet)
    log(
        "done. start a NEW Codex thread (or restart ChatGPT.app) so node_repl picks up the env.",
        quiet=args.quiet,
    )
    return 0


def cmd_repair(args: argparse.Namespace) -> int:
    state = load_state()
    ns = argparse.Namespace(
        allow=state.get("domains") or [],
        preset=None,
        persist=False,
        dry_run=False,
        quiet=True,
    )
    return cmd_install(ns)


def cmd_uninstall(args: argparse.Namespace) -> int:
    unpersist(quiet=args.quiet)
    path = config_toml()
    if path.exists():
        text = path.read_text()
        bin_path = official_node_repl()
        if bin_path is not None and table_span(text, "mcp_servers.node_repl"):
            text = set_key(text, "mcp_servers.node_repl", "command", str(bin_path))
        text = remove_key(text, "mcp_servers.node_repl.env", "BROWSER_USE_SECURITY_MODE")
        if not args.dry_run:
            path.write_text(text)
            log(f"restored node_repl command in {path}", quiet=args.quiet)
    root = plugin_cache() / "unified-computer-use"
    wrap = str(wrapper_path())
    bin_path = official_node_repl()
    if root.exists() and bin_path is not None:
        for mcp in root.glob("*/.mcp.json"):
            data = json.loads(mcp.read_text())
            env = data.get("mcpServers", {}).get("cua_repl", {}).get("env")
            if not isinstance(env, dict):
                continue
            env.pop("BROWSER_USE_SECURITY_MODE", None)
            if env.get("CUA_REPL_NODE_REPL_PATH") == wrap:
                env["CUA_REPL_NODE_REPL_PATH"] = str(bin_path)
            if not args.dry_run:
                mcp.write_text(json.dumps(data, indent=2, ensure_ascii=False) + "\n")
                log(f"restored {mcp}", quiet=args.quiet)
    log("origin allowlists were left in place; delete them manually if you want.", quiet=args.quiet)
    return 0


def live_node_repl() -> list[tuple[str, str]]:
    try:
        pids = subprocess.check_output(["pgrep", "-f", "/cua_node/bin/node_repl"], text=True)
    except subprocess.CalledProcessError:
        return []
    rows = []
    for pid in pids.split():
        try:
            env = subprocess.check_output(["ps", "eww", "-p", pid], text=True, errors="replace")
        except subprocess.CalledProcessError:
            continue
        mode = "<unset>"
        for part in env.replace(" ", "\n").split("\n"):
            if part.startswith("BROWSER_USE_SECURITY_MODE="):
                mode = part.split("=", 1)[1]
                break
        rows.append((pid, mode))
    return rows


def cmd_status(args: argparse.Namespace) -> int:
    print(f"CODEX_HOME          {codex_home()}")
    print(f"wrapper             {wrapper_path()} exists={wrapper_path().exists()}")
    print(f"official node_repl  {official_node_repl()}")
    print(f"LaunchAgent         {launch_agent_path()} exists={launch_agent_path().exists()}")
    cfg = config_toml()
    if cfg.exists():
        text = cfg.read_text()
        span = table_span(text, "mcp_servers.node_repl")
        cmd = None
        mode = None
        if span:
            m = re.search(r'(?m)^command\s*=\s*"(.*)"', text[span[0] : span[1]])
            cmd = m.group(1) if m else None
        env_span = table_span(text, "mcp_servers.node_repl.env")
        if env_span:
            m = re.search(
                r'(?m)^BROWSER_USE_SECURITY_MODE\s*=\s*"(.*)"',
                text[env_span[0] : env_span[1]],
            )
            mode = m.group(1) if m else None
        print(f"config command      {cmd}")
        print(f"config security     {mode}")
        ok = cmd == str(wrapper_path()) and mode == MODE
        print(f"config ok           {ok}")
    else:
        print("config.toml         missing")
        ok = False
    rows = live_node_repl()
    if not rows:
        print("live node_repl      (none)")
    for pid, mode in rows:
        print(f"live pid={pid}      mode={mode}")
    if not ok:
        return 2
    if rows and all(mode != MODE for _, mode in rows):
        print("note: live processes still have the old env; start a new Codex thread.")
        return 3
    return 0


def build_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(
        prog="codex-browser-lab",
        description="Turn on Codex Browser Use local-testing mode (skip aura/site_status).",
    )
    sub = p.add_subparsers(dest="cmd", required=True)

    def add_common(sp: argparse.ArgumentParser) -> None:
        sp.add_argument("--dry-run", action="store_true")
        sp.add_argument("--quiet", action="store_true")

    ins = sub.add_parser("install", help="patch local Codex/ChatGPT config")
    add_common(ins)
    ins.add_argument("--persist", action="store_true", help="macOS LaunchAgent: re-apply after ChatGPT updates")
    ins.add_argument("--preset", choices=sorted(PRESETS), help="origin allowlist preset")
    ins.add_argument("--allow", action="append", default=[], metavar="DOMAIN", help="repeatable, e.g. --allow pixiv.net")
    ins.set_defaults(func=cmd_install)

    st = sub.add_parser("status", help="show whether the patch is active")
    add_common(st)
    st.set_defaults(func=cmd_status)

    un = sub.add_parser("uninstall", help="restore official node_repl; keep origin allowlists")
    add_common(un)
    un.set_defaults(func=cmd_uninstall)

    rp = sub.add_parser("repair", help="re-apply last install (used by LaunchAgent)")
    add_common(rp)
    rp.set_defaults(func=cmd_repair)

    return p


def main(argv: list[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    return args.func(args)


if __name__ == "__main__":
    sys.exit(main())
